CREATE TABLE query_run
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id   BIGINT                                  NOT NULL,
    query_template_id BIGINT                                  NOT NULL,
    status            VARCHAR(30)                             NOT NULL,
    requested_by      VARCHAR(120),
    started_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    finished_at       TIMESTAMP WITHOUT TIME ZONE,
    duration_ms       BIGINT,
    row_count         INTEGER,
    error_message     TEXT,
    CONSTRAINT pk_query_run PRIMARY KEY (id)
);

DROP TABLE organization CASCADE;